/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  prefetchComponentInterface,
} from './components/stencil-component-prefetch/stencil-component-prefetch';

export namespace Components {
  interface ExampleComponent1 {}
  interface ExampleComponent2 {}
  interface StencilComponentPrefetch {
    /**
    * @param components an array of component information to prefetch  [ { tag: 'my-component', props: { myProp: value, otherProp, otherValue } } ]
    */
    'setComponents': (components: prefetchComponentInterface[]) => Promise<void>;
    /**
    * @param delay number - the amount of time to wait before pre-fetching (ms)
    */
    'setDelay': (delay: number) => Promise<void>;
  }
}

declare global {


  interface HTMLExampleComponent1Element extends Components.ExampleComponent1, HTMLStencilElement {}
  var HTMLExampleComponent1Element: {
    prototype: HTMLExampleComponent1Element;
    new (): HTMLExampleComponent1Element;
  };

  interface HTMLExampleComponent2Element extends Components.ExampleComponent2, HTMLStencilElement {}
  var HTMLExampleComponent2Element: {
    prototype: HTMLExampleComponent2Element;
    new (): HTMLExampleComponent2Element;
  };

  interface HTMLStencilComponentPrefetchElement extends Components.StencilComponentPrefetch, HTMLStencilElement {}
  var HTMLStencilComponentPrefetchElement: {
    prototype: HTMLStencilComponentPrefetchElement;
    new (): HTMLStencilComponentPrefetchElement;
  };
  interface HTMLElementTagNameMap {
    'example-component-1': HTMLExampleComponent1Element;
    'example-component-2': HTMLExampleComponent2Element;
    'stencil-component-prefetch': HTMLStencilComponentPrefetchElement;
  }
}

declare namespace LocalJSX {
  interface ExampleComponent1 {}
  interface ExampleComponent2 {}
  interface StencilComponentPrefetch {}

  interface IntrinsicElements {
    'example-component-1': ExampleComponent1;
    'example-component-2': ExampleComponent2;
    'stencil-component-prefetch': StencilComponentPrefetch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'example-component-1': LocalJSX.ExampleComponent1 & JSXBase.HTMLAttributes<HTMLExampleComponent1Element>;
      'example-component-2': LocalJSX.ExampleComponent2 & JSXBase.HTMLAttributes<HTMLExampleComponent2Element>;
      'stencil-component-prefetch': LocalJSX.StencilComponentPrefetch & JSXBase.HTMLAttributes<HTMLStencilComponentPrefetchElement>;
    }
  }
}


